# -------------------------
# Data Configuration
# -------------------------

START_DATE = '2010-01-01'
END_DATE = '2025-01-01'
DATA_FREQUENCY = '1mo'
PERIODS_PER_YEAR = 12

NIFTY50_TICKERS = ['ADANIENT.NS', 'ADANIPORTS.NS', 'APOLLOHOSP.NS', 'ASIANPAINT.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BEL.NS', 'BHARTIARTL.NS', 'CIPLA.NS', 'COALINDIA.NS', 'DRREDDY.NS', 'EICHERMOT.NS', 'ETERNAL.NS', 'GRASIM.NS', 'HCLTECH.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HINDALCO.NS', 'HINDUNILVR.NS', 'ICICIBANK.NS', 'INDIGO.NS', 'INFY.NS', 'ITC.NS', 'JIOFIN.NS', 'JSWSTEEL.NS', 'KOTAKBANK.NS', 'LT.NS', 'M&M.NS', 'MARUTI.NS', 'MAXHEALTH.NS', 'NESTLEIND.NS', 'NTPC.NS', 'ONGC.NS', 'POWERGRID.NS', 'RELIANCE.NS', 'SBILIFE.NS', 'SHRIRAMFIN.NS', 'SBIN.NS', 'SUNPHARMA.NS', 'TCS.NS', 'TATACONSUM.NS', 'TMPV.NS', 'TATASTEEL.NS', 'TECHM.NS', 'TITAN.NS', 'TRENT.NS', 'ULTRACEMCO.NS', 'WIPRO.NS']
NIFTY_MIDCAP50_TICKERS = ['APLAPOLLO.NS', 'AUBANK.NS', 'ASHOKLEY.NS', 'AUROPHARMA.NS', 'BSE.NS', 'BHARATFORG.NS', 'BHEL.NS', 'COFORGE.NS', 'COLPAL.NS', 'CUMMINSIND.NS', 'DABUR.NS', 'DIXON.NS', 'FEDERALBNK.NS', 'FORTIS.NS', 'GMRAIRPORT.NS', 'GODREJPROP.NS', 'HDFCAMC.NS', 'HEROMOTOCO.NS', 'HINDPETRO.NS', 'IDFCFIRSTB.NS', 'IRCTC.NS', 'INDUSTOWER.NS', 'INDUSINDBK.NS', 'JUBLFOOD.NS', 'LUPIN.NS', 'MANKIND.NS', 'MARICO.NS', 'MFSL.NS', 'MPHASIS.NS', 'MUTHOOTFIN.NS', 'NHPC.NS', 'NMDC.NS', 'OBEROIRLTY.NS', 'OIL.NS', 'PAYTM.NS', 'OFSS.NS', 'POLICYBZR.NS', 'PIIND.NS', 'PAGEIND.NS', 'PERSISTENT.NS', 'PHOENIXLTD.NS', 'POLYCAB.NS', 'PRESTIGE.NS', 'SBICARD.NS', 'SRF.NS', 'SUPREMEIND.NS', 'SUZLON.NS', 'TIINDIA.NS', 'UPL.NS', 'YESBANK.NS']
NIFTY_SMALLCAP50_TICKERS = ['AARTIIND.NS', 'ABREL.NS', 'AEGISLOG.NS', 'AFFLE.NS', 'ARE&M.NS', 'AMBER.NS', 'ANGELONE.NS', 'ASTERDM.NS', 'BANDHANBNK.NS', 'CESC.NS', 'CASTROLIND.NS', 'CDSL.NS', 'CHOLAHLDNG.NS', 'CAMS.NS', 'CROMPTON.NS', 'CYIENT.NS', 'DELHIVERY.NS', 'LALPATHLAB.NS', 'FSL.NS', 'FIVESTAR.NS', 'GLAND.NS', 'HSCL.NS', 'IIFL.NS', 'IEX.NS', 'INOXWIND.NS', 'JBCHEPHARM.NS', 'KARURVYSYA.NS', 'KAYNES.NS', 'KEC.NS', 'KFINTECH.NS', 'LAURUSLABS.NS', 'MANAPPURAM.NS', 'MCX.NS', 'NATCOPHARM.NS', 'NBCC.NS', 'NH.NS', 'NAVINFLUOR.NS', 'NEULANDLAB.NS', 'PGEL.NS', 'PNBHOUSING.NS', 'PPLPHARMA.NS', 'POONAWALLA.NS', 'RADICO.NS', 'REDINGTON.NS', 'RPOWER.NS', 'TATACHEM.NS', 'RAMCOCEM.NS', 'WELCORP.NS', 'WOCKPHARMA.NS', 'ZENSARTECH.NS']


STOCK_TICKERS = ['RELIANCE.NS', 'HDFCBANK.NS', 'INFY.NS', 'TCS.NS' , 'ADANIENT.NS', 'ADANIPORTS.NS' , 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BHARTIARTL.NS', 'CIPLA.NS', 'COALINDIA.NS', 'EICHERMOT.NS']


# -------------------------
# Black–Litterman Parameters
# -------------------------

RISK_FREE_RATE_ANNUAL = 0.06
RISK_FREE_RATE_PERIODIC = RISK_FREE_RATE_ANNUAL / PERIODS_PER_YEAR

IMPLIED_RISK_AVERSION = 2.5

TAU = 0.05  # Prior uncertainty scaling


# -------------------------
# HMM Parameters
# -------------------------

NUM_MARKET_REGIMES = 3
HMM_TRAINING_PERIOD_YEARS = 5


# -------------------------
# Plotting
# -------------------------

PLOT_SAVE_PATH = 'plots/'