#config

START_DATE = "2013-01-01"
END_DATE = "2024-01-01"
TICKER = ['RELIANCE.NS', 'HDFCBANK.NS', 'BHARTIARTL.NS', 'TCS.NS', 'ICICIBANK.NS',
    'SBIN.NS', 'INFY.NS', 'BAJFINANCE.NS', 'LT.NS', 'HINDUNILVR.NS',
    'MARUTI.NS', 'M&M.NS', 'HCLTECH.NS', 'SUNPHARMA.NS', 'ITC.NS',
    'KOTAKBANK.NS', 'AXISBANK.NS', 'TITAN.NS', 'ULTRACEMCO.NS', 'NTPC.NS',]
FREQUENCY = "M"

RISK_FREE_RATE = 0.04
NUM_REGIMES = 3
ROLLING_WINDOW = 36

TRANSACTION_COST = 0.001
MAX_WEIGHT = 0.15
LONG_ONLY = True
