version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  python_app:
    build: .
    container_name: portfolio_app
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  ollama_data: